# Generated by Django 5.1.1 on 2024-12-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_chat_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
